// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDW-T8iVpW9vF0X-HQ8Z_5QKBQwP5WaoGo',
    appId: '1:945946832817:web:a4556bfffe08325221d790',
    messagingSenderId: '945946832817',
    projectId: 'mahdhiya-fashion-store',
    authDomain: 'mahdhiya-fashion-store.firebaseapp.com',
    storageBucket: 'mahdhiya-fashion-store.firebasestorage.app',
    measurementId: 'G-9WEZN97BCJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7YO7MmB6pNT3e5teOUvHHwcn_VK85rpk',
    appId: '1:945946832817:android:711e945656bbcaf221d790',
    messagingSenderId: '945946832817',
    projectId: 'mahdhiya-fashion-store',
    storageBucket: 'mahdhiya-fashion-store.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLizsyZEzr3q6jwejXDRc62eg88_qH78E',
    appId: '1:945946832817:ios:5d009ac6ce99d2eb21d790',
    messagingSenderId: '945946832817',
    projectId: 'mahdhiya-fashion-store',
    storageBucket: 'mahdhiya-fashion-store.firebasestorage.app',
    iosClientId: '945946832817-vl4ltii10kiq5vc02ne8kgf5kn5r23iq.apps.googleusercontent.com',
    iosBundleId: 'com.example.mahdhiyaFashionStore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDLizsyZEzr3q6jwejXDRc62eg88_qH78E',
    appId: '1:945946832817:ios:5d009ac6ce99d2eb21d790',
    messagingSenderId: '945946832817',
    projectId: 'mahdhiya-fashion-store',
    storageBucket: 'mahdhiya-fashion-store.firebasestorage.app',
    iosClientId: '945946832817-vl4ltii10kiq5vc02ne8kgf5kn5r23iq.apps.googleusercontent.com',
    iosBundleId: 'com.example.mahdhiyaFashionStore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDW-T8iVpW9vF0X-HQ8Z_5QKBQwP5WaoGo',
    appId: '1:945946832817:web:070db445b245297421d790',
    messagingSenderId: '945946832817',
    projectId: 'mahdhiya-fashion-store',
    authDomain: 'mahdhiya-fashion-store.firebaseapp.com',
    storageBucket: 'mahdhiya-fashion-store.firebasestorage.app',
    measurementId: 'G-EKPJEY2VEF',
  );
}
