// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMlujRjI4yoRQ5Bpfk6PrNtGrjTSrFuMw',
    appId: '1:328397482467:web:637f49d0a8636a953418d6',
    messagingSenderId: '328397482467',
    projectId: 'mahmooth-fashion-store',
    authDomain: 'mahmooth-fashion-store.firebaseapp.com',
    storageBucket: 'mahmooth-fashion-store.firebasestorage.app',
    measurementId: 'G-X8Z5JWX3TH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFwICqxF-U9By5-TZ0_sx6UZF1o6FPn6g',
    appId: '1:328397482467:android:15aeec82ab45ae273418d6',
    messagingSenderId: '328397482467',
    projectId: 'mahmooth-fashion-store',
    storageBucket: 'mahmooth-fashion-store.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUsQcG9zhpXk2iPQW9J5xVNWF7WPGQ15I',
    appId: '1:328397482467:ios:d217aa6b4851e48f3418d6',
    messagingSenderId: '328397482467',
    projectId: 'mahmooth-fashion-store',
    storageBucket: 'mahmooth-fashion-store.firebasestorage.app',
    iosBundleId: 'com.example.mahdhiyaFashionStore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCUsQcG9zhpXk2iPQW9J5xVNWF7WPGQ15I',
    appId: '1:328397482467:ios:d217aa6b4851e48f3418d6',
    messagingSenderId: '328397482467',
    projectId: 'mahmooth-fashion-store',
    storageBucket: 'mahmooth-fashion-store.firebasestorage.app',
    iosBundleId: 'com.example.mahdhiyaFashionStore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCMlujRjI4yoRQ5Bpfk6PrNtGrjTSrFuMw',
    appId: '1:328397482467:web:0a35214267b198853418d6',
    messagingSenderId: '328397482467',
    projectId: 'mahmooth-fashion-store',
    authDomain: 'mahmooth-fashion-store.firebaseapp.com',
    storageBucket: 'mahmooth-fashion-store.firebasestorage.app',
    measurementId: 'G-5S02NQ894V',
  );

}